wallets:
  - name: wallet-1
    address: <address>

# optional
liquid_pool: null

validators:
  # Validator with nominators pools
  - name: validator-1
    address: <address>
    pools:
      - <address>
      - <address>

  # Native validator (without pools and nominators)
  - name: validator-4
    address: <address>

  # Validator with liquid controllers
  - name: validator-5
    address: <address>
    controllers:
      - <address>
      - <address>

  # Validator with single pool
  - name: validator-6
    address: <address>
    single_pool: <address>
